d_project/accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
      path('signup/', views.signup_view, name='SignUp'),
      path('login/', views.login_view, name='Login'),
      path('logout/', views.logout_view, name='Logout')



]

d_project/d_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from movies import views as movies_view




urlpatterns = [

    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('', movies_view.movies_list, name="home")


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

d_project/movies/urls.py
from django.urls import path
from . import views
app_name = "movies"
urlpatterns = [
    path('', views.movies_list, name='home'),
    path('create/', views.article_create, name='create'),
    path('<slug:slug>/', views.movies_detail, name='detail'),
    path('<slug:slug>/like', views.like_view, name='like'),
    path('<slug:slug>/review', views.sub_review, name='review'),



]

d_project/accounts/models.py
from django.db import models

# Create your models here.

d_project/movies/models.py
from django.db import models
from django.contrib.auth.models import User

CATEGORY_CHOICE = (
    ('A','Action'),
    ('D', 'Drama')
)

class Play(models.Model):
    title = models.CharField(max_length=150)
    plot = models.TextField(max_length=900)
    slug = models.SlugField(unique=True, null=True)
    cast = models.CharField(max_length=500, default=0)
    category = models.CharField(choices=CATEGORY_CHOICE, max_length=10)
    image = models.ImageField(upload_to='movie')
    year = models.DateTimeField()
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

RATE_CHOICES = [
    (1, '1 - Trash'),
    (2, '2 - Bad'),
    (3, '3 - OK'),
    (4, '4 - Very Good'),
    (5, '5 - Master Piece'),
]


class Review(models.Model):



    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    movie = models.ForeignKey(Play, blank=True, null=True, on_delete=models.CASCADE)
    text = models.TextField()
    likes = models.ManyToManyField(User, related_name='blog_comment')
    class Meta:
        unique_together = ['user','movie']


    def count_likes(self):
        return self.likes.count()

    def __str__(self):
        return f"{self.movie.title} 'User:' {self.user}"

d_project/movies/forms.py
from typing import Type
from django import forms
from .import models
from .models import Play
from .models import Review
class CreatePlay(forms.ModelForm):
    class Meta:
        model = models.Play
        fields = ["title", "plot", "slug", "cast", "category", "image", "year"]

class CreateReview(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = ["text"]

d_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm



def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:home")
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {"form":form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("movies:home")
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {"form":form})



def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("movies:home")

d_project/movies/views.py
from django.shortcuts import render, redirect, reverse
from .models import Play, Review
from django.contrib.auth.decorators import login_required
from . import forms
from django.http import HttpResponseRedirect

def movies_list(request):
    article = Play.objects.all().order_by('year')
    return render(request, "articles/movies_list.html", {"articles":article})


def movies_detail(request, slug):
    articles = Play.objects.get(slug=slug)
    all_reviews = Review.objects.all().order_by('movie')
    print(all_reviews)
    isReviewAllowed = check_user_review(request, slug)
    print(isReviewAllowed)
    return render(request, "articles/movies_detail.html", {"articles":articles,'all_reviews': all_reviews, 'isReviewAllowed': isReviewAllowed})



@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == "POST":
        form = forms.CreatePlay(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("movies:home")
    else:
            form = forms.CreatePlay()
    return render(request, "articles/article_create.html", {"form":form})

@login_required(login_url="/accounts/login/")
def sub_review(request, slug):
    form = forms.CreateReview(request.POST)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        show = Play.objects.get(slug=slug)
        instance.movie = show
        instance.save()
        return redirect("movies:detail", slug=slug)
    else:
        form = forms.CreateReview()
        return render(request, "articles/review.html", {"form":form, "slug":slug})




def check_user_review(request, slug):
    check = Review.objects.values_list('user', 'movie')
    test = Review.objects.count()
    watch = Play.objects.get(slug=slug)
    if test == 0:
        return True
    else:
      for user, movie in check:
          #print(watch.id)
          #print(movie)
          if user == request.user.id and movie == watch.id:
              return False
          else:
              return True




def like_view(request, slug):
    like = Review.objects.get(id=request.POST.get('review_id'))
    like.likes.add(request.user)
    return HttpResponseRedirect(reverse('movies:detail', args=[slug]))

d_project/templates/accounts/login.html
{% extends 'base.html' %}
{% block content%}
<h1>Login</h1>
<form class="site-form" action="/accounts/login/" method="post">
    {% csrf_token %}
   {{ form }}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
   <input type="submit" value="Login">
</form>
{% endblock %}

d_project/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content%}
<h1>SignUp</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
   {{ form }}
   <input type="submit" value="Signup">
</form>
{% endblock %}

d_project/templates/articles/article_create.html
{% extends 'base.html' %}
{% block content%}
<div class="create-article">
    <h2>New Movie!</h2>
    <form class="site-form" action="{% url 'movies:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create">
    </form>
</div>
{% endblock %}

d_project/templates/articles/movies_detail.html
{% extends 'base.html' %}
{% block content %}
<img src="{{ articles.image.url }}" width="200px" height="300" style="display: inline-block;" >
<div id="movie_plot">
      <h2>{{articles.title}}</h2>
      <p>{{articles.plot}}</p>
    {{articles.category}}
   <p>{{articles.cast}}</p>
 <p>{{articles.year}}</p>

</div>
{% if isReviewAllowed == True %}
<div class="isReviewAllowed">
        <div class="nav_button"><a class="new_movie" href="{% url 'movies:review' slug=articles.slug %}">Create Review</a></div>
</div>
{% endif %}
{% for review in all_reviews %}
  {% if review.Review == movie.title %}
<div class="all_reviews">
            <div class="review">
                <p><span style="font-weight: normal;">Reviewed by: </span> {{review.user}} </p>
                <p><span style="font-weight: normal;">Description: </span>{{review.text}}</p>
                <form style="text-align: center;" action="{% url 'movies:like' slug=articles.slug %}" method="post">
                {% csrf_token %}
                <button style="color: white; background: #104e89;" type="submit", name="review_id", value="{{ review.id }}", class="btn btn-primary btn-sm">Like</button> {{review.count_likes}}
                </form>
            </div>
        {% elif review.movie.title == movie.title %}
            <div class="review">
            <p><span style="font-weight: normal;">Reviewed by: </span> {{review.user}} </p>
            <p><span style="font-weight: normal;">Description: </span>{{review.text}}</p>
            </div>

     {% endif %}
    {% endfor %}
</div>
{% endblock %}

d_project/templates/articles/movies_list.html
{% extends 'base.html' %}
{% block content%}
<h1>Movies To Watch</h1>
{% for article in articles %}
  <a href="{% url 'movies:detail' article.slug %}">
    <img src="{{ article.image.url }}" width="200" height="300"></a>
{% endfor %}
{% endblock %}

d_project/templates/articles/review.html
{% extends 'base.html' %}
{% block content %}
<h2>Create Review</h2>
<div class="nav_button"><a class="new_movie" href="{{request.META.HTTP_REFERER}}">Return:</a></div>
<form class="site-form" action="{% url 'movies:review' slug=slug %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    {{field.label_tag}}
    <div>{{field}}</div>
    {% endfor %}
    <input type="submit" value="Create">
</form>
{% endblock %}

d_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MOVIES</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">


</head>
<body>
<div class="wrapper">
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="HP">

        <h1><a href="{% url 'movies:home' %}" ><i class="bi bi-emoji-sunglasses-fill"></i>HomeTV</a></h1>
        <h2 id="hagai"></h2>

    </a>
  </div>
</nav>
       <nav>
            <ul>

               {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:Logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
            <li><a href="{% url 'movies:create' %}" class="highlight"> Add New Movie!</a> </li>


             {% else %}

            <li><a href="{% url 'accounts:Login' %}">Login</a></li>
            <li><a href="{% url 'accounts:SignUp' %}">Signup</a></li>

             {% endif %}

            </ul>
        </nav>

     {% block content %}
     {% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</div>
</body>
</html>